
CREATE TABLE tb_notes (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title VARCHAR(100) NOT NULL,

    content TEXT,

    created_at TIMESTAMP NOT NULL,

    updated_at TIMESTAMP
);